apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: $COMPOSE_PROJECT_NAME
spec:
  replicas: $NUMBER_PODS
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: Always
        # env:
        #   - name: GF_SECURITY_ADMIN_USER
        #     valueFrom:
        #       secretKeyRef:
        #         name: grafana
        #         key: admin
        #   - name: GF_SECURITY_ADMIN_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: grafana
        #         key: admin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          # - mountPath: /etc/grafana/provisioning/dashboards
          #   name: grafana-dash
      restartPolicy: Always

      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        # - name: grafana-dash
        #   configMap:
        #     name: grafana-dash
