apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
  labels:
    app: prometheus
    component: node-exporter
spec:
  selector:
    app: prometheus
    component: node-exporter
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
